### ISSUE TITLE
Outrageous !!!

### ISSUE THREAD

**Issue by julian70400** [GDATASoftwareAG/nextcloud-gdata-antivirus#105]
I saw this app in the Nextcloud applications, and I thought it might be interesting to test it as a complement to my ClamAV setup. What a nightmare!!!

I tried to create an account, and you end up on a page in German. Great, considering I, like many people, didn’t take German as a first language... Anyway, I still managed to validate my account. I received the confirmation email and clicked the verification link, but it was IMPOSSIBLE to log into their interface.

I went back to the app integrated into Nextcloud, it accepts most of the settings but doesn't confirm anything... You don't know which authentication method to choose. I tried both with my credentials, but it was impossible to run a scan—every time, I was told that I wasn’t properly authenticated!

But that's not even the worst part! The worst part is that, in the meantime, the app automatically starts tagging ALL the files in the instance... Around 25,000 files in my case! And I got buried, along with all my users, under a deluge of notifications! Until I received an alert from the Nextcloud push gateway, warning me that they were cutting off my free notifications because I exceeded the quota!

Outrageous!!! I’m going to report this app to Nextcloud!!

**Comment by GermanCoding** [comment]
Hi @julian70400,

Firstly, we would like to apologise for any inconvenience caused. We have recorded your feedback and are looking into possible improvements. We are taking this seriously and are already working on improved documentation and user help.

Regarding the settings, we recommend that you read this repositories README, specifically the [settings ](https://github.com/GDATASoftwareAG/nextcloud-gdata-antivirus?tab=readme-ov-file#settings) section. It explains how the settings and tags work. In order to authenticate with the GData VaaS service, you need to select the "Resource Owner Password Flow".

The user registration page can be switched to English via the language flag button in the upper right corner. There is currently no actual user UI to login to, other than registration.

By default, the app tags not yet scanned files with the "unscanned" tag. This is a safety feature such that users know which files have already been scanned, in particular if the app was only recently installed. However, this behavior can be disabled in the settings. You can also turn off automatic scanning, or set a filter ("scan only this") to limit the amount of files scanned (at the expense of security). You can use the "reset all tags" button to remove all tags the app has already set.

If you have further questions or problems, our team is also available for a free of charge Zoom conference to discuss. You can mail us at vaas@gdata.de for the link (we can suggest time slices for tomorrow 10-11 or 14-15 CEST if you wish).

**Comment by GermanCoding** [comment]
We have significantly reduced the number of activity events generated in release 29.4.0: Only files detected as malicious and potentially unwanted program (pup) will have activities attached to them. Thus, unscanned or clean tags should no longer cause a flood in notifications. We believe that this should resolve the original issue.

**Comment by julian70400** [comment]
Thank you for your work, follow-up, and responsiveness; it is greatly appreciated here. Will git it a second try.
