### ISSUE TITLE
Unscanned tag is constantly deleted

### ISSUE THREAD

**Issue by lennartdohmann** [GDATASoftwareAG/nextcloud-gdata-antivirus#57]
## Expected

If the "Disable Unscanned tag" setting is activated, this tag should not exist for the end user, so it should not be displayed in logs, activities or the tag menu.

## Actual

If the "Disable Unscanned Tag" setting is activated, the unscanned tag is permanently recreated by the background jobs and deleted again immediately. This recreation and deletion then appears in both the logs and the Activities app and spams server administrators and important information is lost.

**Comment by lennartdohmann** [comment]
This bug affects all app versions

**Comment by unglaublicherdude** [comment]
This is not only related to the unscanned tag. Even the other tags get constantly [deleted when files get scanned](https://github.com/GDATASoftwareAG/nextcloud-gdata-antivirus/blob/main/lib/Service/VerdictService.php#L112).
That is due to the fact, the tagFile function always removes all tags instead of first.

![image](https://github.com/GDATASoftwareAG/nextcloud-gdata-antivirus/assets/13208176/45fe7a0b-53cf-45ac-b8dd-3652d6ba9f6f)

Yes I agree that its not constantly like the unscanned tag, but still a bit annoying.

![image](https://github.com/GDATASoftwareAG/nextcloud-gdata-antivirus/assets/13208176/6d0089a3-a086-47be-8ad5-eff1a53fba4b)

**Comment by unglaublicherdude** [comment]
Ah. It is this:
https://github.com/GDATASoftwareAG/nextcloud-gdata-antivirus/blob/main/lib/Service/TagUnscannedService.php#L42-L46

**Comment by unglaublicherdude** [comment]
the getTag is called without the second parameter, so it will always create it again.

**Comment by unglaublicherdude** [comment]
The Problem is actually in the Scan Service:

https://github.com/GDATASoftwareAG/nextcloud-gdata-antivirus/blob/main/lib/Service/ScanService.php#L44

When it runs, it will always recreate the tag. And then the unscanned-tag-job will remove it again.

**Comment by unglaublicherdude** [comment]
![image](https://github.com/GDATASoftwareAG/nextcloud-gdata-antivirus/assets/13208176/525d8dbe-6308-4d28-a461-f7450641ded7)

Ill open a PR now. This is what the changes look like in the activity log.

Still in Draft mode, because I would like to add tests too.
